### ISSUE TITLE
dashboard no data

### ISSUE THREAD

**Issue by lannyMa** [nccgroup/kube-auto-analyzer#2]
```
$ docker run -v /data:/data raesene/kube_auto_analyzer -c /data/admin.conf -s 192.168.x.x -i 8080 --html -r testdock
/usr/lib/ruby/gems/2.3.0/gems/kube_auto_analyzer-0.0.9/lib/kube_auto_analyzer/reporting.rb:212:in `html_report': undefined method `index' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/gems/2.3.0/gems/kube_auto_analyzer-0.0.9/lib/kube_auto_analyzer.rb:104:in `execute'
	from /usr/lib/ruby/gems/2.3.0/gems/kube_auto_analyzer-0.0.9/bin/kubeautoanalyzer:91:in `<top (required)>'
	from /usr/bin/kubeautoanalyzer:22:in `load'
	from /usr/bin/kubeautoanalyzer:22:in `<main>'

```

![image](https://user-images.githubusercontent.com/16549395/33541100-cc35a1fa-d908-11e7-863f-0561e2f343ed.png)

i do not kown the what is the admin.conf, there is no data in my dashboard ,help me?
thx

**Comment by raesene** [comment]
Hi, 

So a couple of questions and a suggestion.  

Question
--
 - What k8s distribution and version are you using?  If it's a public one I can download and see if I can replicate your issue
 - The options you're supplying are for both using a kubeconfig file and also the insecure port, you shouldn't need to mix those (it'll be one or the other), which do you have enabled?

Suggestion
--

Assuming you've got the insecure port open and available on that ip address and port, if you use something like 

`docker run -v /data:/data raesene/kube_auto_analyzer -s 192.168.x.x:8080 -i --html -r testdock`

that should work.

**Comment by raesene** [comment]
Not heard anything back in several months, so I'll assume that this isn't still a live issue :) Feel free to comment/re-open if it is...
